#!/usr/bin/env ruby

require 'rubygems'

# Load hbase client libs generated by thrift
$LOAD_PATH << File.join(File.dirname(__FILE__), 'hbase')
require 'hbase'

#--------------------------------------------------------------------------------
# Connect to hbase
socket = ::Thrift::Socket.new('hbase.server', 9090, 5) # server, port, timeout
transport = ::Thrift::BufferedTransport.new(socket)
transport.open

protocol = ::Thrift::BinaryProtocol.new(transport)
client = Apache::Hadoop::Hbase::Thrift::Hbase::Client.new(protocol)

#--------------------------------------------------------------------------------
# Get a row from hbase
rows = client.getRowWithColumns('table_name', '123', []) # Get all columns for row_id='123'
if rows && rows.any?
  puts "ROW_ID='123', DATA=#{rows.first.columns.inspect}"
else
  puts "No rows found"
end
